name: Update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "1 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v5
      with:
        python-version: ’3.10’
        architecture: 'x64'
    - name: Create local changes
      run: |
        pip install -r requirements.txt
        python generate.py
    - name: Commit changes
      run: |
        git config --local user.email "update-bot@update-bot.org"
        git config --local user.name "README Update Bot"
        git commit -m "Update today's image from NASA on $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
